// Code generated by capnpc-go. DO NOT EDIT.

package main

import (
	powerbox "zenhack.net/go/sandstorm/capnp/powerbox"
	capnp "zombiezen.com/go/capnproto2"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

// Constants defined in pb-requests.capnp.
var (
	DirectoryReq   = powerbox.PowerboxDescriptor{Struct: capnp.MustUnmarshalRoot(x_f7eee63280552269[0:56]).Struct()}
	RwDirectoryReq = powerbox.PowerboxDescriptor{Struct: capnp.MustUnmarshalRoot(x_f7eee63280552269[56:112]).Struct()}
)

const schema_f7eee63280552269 = "x\xda\x12X\xed\xc0d\xc8\xaa\xce\xc2\xc0\x10h\xc0\xca" +
	"\xf6\xff\xd4\xe1\xc8\x84\x99G\xec\x971\x08\x0a\xb1\xfc\xcf" +
	"T\x0am0z\xf6\xee;\x03\x03\xa3\xf1OF.F" +
	"aN&v\x06\x86`\x16&f\xc6`\x01&&F" +
	"\x06\x86\xff\xe7f\xf9><\x97\xc6\xfc\x02]\xbd\xb0(" +
	"\xd3/aE\xb0r\x19\x90r\x0d\x90\xf2\xbc\xff\x05I" +
	"\xbaE\xa9\x85\xa5\xa9\xcc\xc5%\xc5z\xc9\x89\x05y\x05" +
	"VE\xe5.\x99E\xa9\xc9%\xf9E\x95A\xa9\x85\x0c" +
	"\x0c\x01\x8c\x8c\x8c\x02\xff#d\x8e\xef_\xcc\x7f\xfe-" +
	"\x03\x03#\xa3\x00X\x90\x81A\x90Q<\x90\x85\x91\xf1" +
	"\xff\x9f\xfbG\xbf\x9ai\xfc\xbb\xcf\xc0\xc0\x007\x90\x09" +
	"a`\x0a\xd88{\x88yD\x98\xf6\xa0\xd2=\xc4\xd2" +
	"\xe0\x1c\x03\x03\x03 \x00\x00\xff\xff\xf4\xf5QT"

func init() {
	schemas.Register(schema_f7eee63280552269,
		0xa63fc4996059c3ca,
		0xe80366cee14d9ace)
}

var x_f7eee63280552269 = []byte{
	0, 0, 0, 0, 6, 0, 0, 0,
	0, 0, 0, 0, 1, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 23, 0, 0, 0,
	4, 0, 0, 0, 1, 0, 1, 0,
	252, 224, 121, 71, 84, 57, 48, 206,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 6, 0, 0, 0,
	0, 0, 0, 0, 1, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 0, 0, 0, 23, 0, 0, 0,
	4, 0, 0, 0, 1, 0, 1, 0,
	252, 223, 197, 245, 54, 40, 254, 223,
	0, 0, 0, 0, 0, 0, 0, 0,
}
